      SUBROUTINE PREPROC_KSC(NETWORK_ID,FILELIST,BYEAR,VERBOSE)

C***********************************************************************
C*    Preprocess KSC data
C***********************************************************************

      INCLUDE 'preproc.par'
C***  MODULE FOR PREPROCESSING KSC RAW DATA
      CHARACTER*4 G_NUMBER
      INTEGER*4 YR,YR4,MON,DAY,JDAY,HR,MIN,SEC
      
C***  OPEN FILE LIST CONTAINING INPUT FILES TO BE PROCESSED
      
      IUNIT = 4
      READ(BYEAR,1)YR
 1    FORMAT(I2)
      OPEN(UNIT=2,FILE = FILELIST,STATUS = 'OLD')
      
 2    READ(2,10,END=9999) IFILE
      
C***  SUBROUTINE GET_SITE RETURNS GAUGE NUMBER.  THIS SUBROUTINE IS CALLED
C***  WHEN GAUGE NUMBER CANNOT BE OBTAINED FROM FILENAME.  IN THIS CASE,
C***  THE MODULE GETS G_NUMBER FROM SITELIST FILE BY KEYING ON GNAME.
      
      CALL GET_SITE(NETWORK_ID,IFILE,G_NUMBER,IFIND)
      IF(IFIND.EQ.0)GOTO 2
C***  INTERNAL WRITE OF OUTPUT FILE NAME
      
 10   FORMAT(A60)

C***  Name output file

      CALL NAMEFILE(NETWORK_ID,IFILE,G_NUMBER,BYEAR,OFILE)
      WRITE(6,'("Writing to File: ",A60)') OFILE
      OPEN(UNIT = IUNIT,FILE = OFILE, STATUS = 'UNKNOWN')
      OPEN(UNIT = 3,FILE=IFILE,STATUS='OLD')

 5    READ(3,17,END = 999)YR4,JDAY,HR,MIN,SEC,RAIN
      YR = YR4 - 1900

 17   FORMAT(1X,I4,I3,3(1X,I2),17X,F4.2)

      
      CALL GET_DATE(JDAY,DAY,MON,YR)
      WRITE(IUNIT,16)YR,MON,DAY,HR,MIN,SEC,RAIN
 16   FORMAT(6(I2.2,1X),F7.2)      
      
      GOTO 5
 999  CONTINUE
      
      GOTO 2
 9999 CONTINUE
      
      
      RETURN
      END
