      SUBROUTINE PREPROC_SFL(NETWORK_ID,FILELIST,BYEAR,VERBOSE)

      INCLUDE 'preproc.par'
      CHARACTER*4 G_NUMBER
      CHARACTER*7 SITE
      CHARACTER*2 CYR

      INTEGER*4 YR,MON,DAY,HR,MIN,LASTYR
      INTEGER*4 HROFF,MINOFF
      REAL*4    RR

      HROFF  = 5                !TIME DIFFERENCE BETWEEN EST AND UTC
      MINOFF = 0

      READ(BYEAR,2)IBYR
 2    FORMAT(I2)
      YR = IBYR
 3    OPEN(UNIT = 1,FILE = FILELIST,STATUS = 'OLD')
 4    READ(1,10,END = 999) IFILE
 10   FORMAT(A60)
      OPEN(UNIT = 2,FILE = IFILE,STATUS = 'OLD')

C**** CALL GET_SITE (I.E. GAUGE NUMBER [CHAR*4])
C**** CALL NAMEFILE (I.E. GENERATE OUTPUT FILE NAME)
      CALL GET_SITE(NETWORK_ID,IFILE,G_NUMBER,IFIND)
      CALL NAMEFILE(NETWORK_ID,IFILE,G_NUMBER,BYEAR,OFILE)
C**** OPEN OUTPUT FILE

      OPEN(UNIT = 3,FILE = OFILE,STATUS = 'UNKNOWN')
C**** READ ASCII INPUT DATA FILE

 5    READ(2,11,END=99)SITE,YR,MON,DAY,HR,MIN,RR
      IF(RR.LT..010)then
         write(6,'(a4)')g_number
         write(6,*)YR,MON,DAY,HR,MIN,RR
         GOTO 5
      endif
      IF(MOD(YR,4).EQ.0)THEN
         LEAP = 1
      ELSE
         LEAP = 0
      ENDIF
      JDAY = JULDAY(YR,MON,DAY)
      CALL ANY2UTC(HROFF,MINOFF,LEAP,YR,JDAY,HR,MIN)
      CALL GET_DATE(JDAY,DAY,MON,YR)
 11   FORMAT(A7,1X,I4,I2,I2,1X,I2,I2,2X,F7.3)
      IF(YR.GT.LASTYR)THEN
         CLOSE(3)
         WRITE(CYR,8)YR
 8       FORMAT(I2)
         CALL NAMEFILE(NETWORK_ID,IFILE,G_NUMBER,CYR,OFILE)
         OPEN(UNIT = 3,FILE = OFILE,STATUS = 'UNKNOWN')
      ENDIF
      WRITE(3,20) YR,MON,DAY,JDAY,HR,MIN,RR
 20   FORMAT(I4,2(1X,I2),1X,I3,1X,I2,1X,I2,F7.2)
      GOTO 5
 99   CONTINUE
      GOTO 4
 999  CONTINUE

      RETURN
      END
